meta_product_name: "GoodLook Barbershop"
meta_title: "GoodLook Barbershop"
meta_description: "Najbolji Barbershop u gradu. Najbolje usluge sa stilom"
meta_image: "goodlookpng.webp" # should exist in `app/assets/images/`
